### ISSUE TITLE
`<key>:<opt_side>` schema (`key=val` same as `key:both=val`)

### ISSUE THREAD

**Issue by tordans** [a-b-street/osm2lanes#49]
Looking at https://a-b-street.github.io/osm2lanes/ I see

- `sidewalk=both` works
- `sidewalk:left=yes` works
- `sidewalk:right=yes` works
- `sidewalk:both=yes` _does not work, yet_

AFAIK, for all currently accepted tags(*) the the `:both` tagging is supported whenever there is a `:left|right` version and the version of the tag without a side is an implicit `:both`.

---

*) I know of one exception, which is the WIP separation schema https://wiki.openstreetmap.org/wiki/Proposed_features/cycleway:separation

> If no side is given, the side towards the strongest traffic user is meant by default (usually towards a road with motor vehicles – in countries with right-hand traffic usually on the left-hand side of the cycle path).

(PS: I suggest commenting on that proposal in case you find this too complex for data consumers to handle; I tried to raise this issue before, but with little success :-))

---

Of topic: Are issues like this helpful? Or is it better to wait for a while and test once you are happy with a release?

**Comment by droogmic** [comment]
Well spotted, we are indeed missing a case at https://github.com/a-b-street/osm2lanes/blob/main/rust/osm2lanes/src/transform/tags_to_lanes/foot_shoulder.rs#L25.

> Off topic: Are issues like this helpful? Or is it better to wait for a while and test once you are happy with a release?

This issue is helpful, because I _thought_ I had covered sidewalks correctly.

In general, maybe wait a few more weeks, as the implementation is significantly incomplete. Busways for example are still only partially implemented.
https://github.com/a-b-street/osm2lanes/blob/main/rust/osm2lanes/src/transform/tags_to_lanes/bus.rs#L110

Alternatively: contribute a test case, with all three languages disabled, because we will eventually try to have all test cases working.

**Comment by droogmic** [comment]
Fixed in PR #51
